import { z } from "zod";

export const ConsentOption = z.enum(["Y", "N", "I", "D"]);
export const FinalExamOption = z.enum(["Y", "N", "L"]);

export const ComponentType = z.enum([
  "LEC",
  "DIS",
  "LAB",
  "SEM",
  "ACT",
  "INS",
  "LNG",
  "T/D",
  "PRA",
  "CLK",
  "WKS",
  "ITR",
  "COL",
  "LBS",
  "API",
  "ISS",
  "ISF",
  "SCS",
  "IDS",
  "CAS",
  "RES",
  "RSC",
  "SIM",
  "CLN",
  "TUT",
  "PRC",
]);

export const EnrollStatus = z.enum(["Open", "Closed"]);
export const InstructorRole = z.enum(["PI", "TA", "SI", "GP"]);
export const EffectiveStatus = z.enum(["A", "I"]);
export const AcademicCareer = z.enum(["UG", "GR", "PHD", "MED", "GSB", "LAW"]);

/* =========================
   Canonical enums
   ========================= */

export const GradingOption = z.enum([
  "Credit/No Credit",
  "GSB Letter Graded",
  "GSB Pass/Fail",
  "GSB Student Option LTR/PF",
  "Law Honors/Pass/Restrd Cr/Fail",
  "Law Mandatory Credit 3K",
  "Law Mandatory P/R/F",
  "Law Mixed H/P/R/F or MP/R/F",
  "Law Student Option NM/KE",
  "Law Student Option NM/KM",
  "Letter (ABCD/NP)",
  "Letter or Credit/No Credit",
  "Letter or Credit/No Credit Exception",
  "Medical Option (Med-Ltr-CR/NC)",
  "Medical Satisfactory/No Credit",
  "Medical School MD Grades",
  "NQF Scale",
  "Non-Graded Component",
  "Satisfactory/No Credit",
  "TGR",
  "RO Satisfactory/Unsatisfactory",
  "MED Letter Graded",
  "Graded",
]);

export const GER = z.enum([
  "College",
  "GER:DB-EngrAppSci",
  "GER:DB-Hum",
  "GER:DB-Math",
  "GER:DB-NatSci",
  "GER:DB-SocSci",
  "GER:EC-AmerCul",
  "GER:EC-EthicReas",
  "GER:EC-Gender",
  "GER:EC-GlobalCom",
  "GER:IHUM-1",
  "GER:IHUM-2",
  "GER:IHUM-3",
  "Language",
  "THINK",
  "WAY-A-II",
  "WAY-AQR",
  "WAY-CE",
  "WAY-EDP",
  "WAY-ER",
  "WAY-FR",
  "WAY-SI",
  "WAY-SMA",
  "Writing 1",
  "Writing 2",
  "Writing SLE",
]);

/* =========================
   Hard-coded catalogs
   ========================= */

export const SUBJECTS = [
  "AA",
  "ACCT",
  "AFRICAAM",
  "AFRICAST",
  "ALP",
  "AMELANG",
  "AMHRLANG",
  "AMSTUD",
  "ANES",
  "ANTHRO",
  "APPPHYS",
  "ARABLANG",
  "ARCHLGY",
  "ARMELANG",
  "ARTHIST",
  "ARTSINST",
  "ARTSTUDI",
  "ASLLANG",
  "ASNAMST",
  "ATHLETIC",
  "BIO",
  "BIOC",
  "BIODS",
  "BIOE",
  "BIOHOPK",
  "BIOMEDIN",
  "BIOPHYS",
  "BIOS",
  "BMDS",
  "BMP",
  "BUSGEN",
  "CATLANG",
  "CBIO",
  "CEE",
  "CHEM",
  "CHEMENG",
  "CHRKELNG",
  "CHILATST",
  "CHINA",
  "CHINLANG",
  "CHPR",
  "CLASSICS",
  "CME",
  "COLLEGE",
  "COMM",
  "COMPLIT",
  "COMPMED",
  "CS",
  "CSB",
  "CSRE",
  "CTL",
  "CTS",
  "CZECLANG",
  "DANCE",
  "DATASCI",
  "DBIO",
  "DERM",
  "DESIGN",
  "DESINST",
  "DLCL",
  "DUTCHLNG",
  "EALC",
  "EARTHSYS",
  "EASTASN",
  "EBS",
  "ECON",
  "EDUC",
  "EE",
  "EFSLANG",
  "EMED",
  "ENERGY",
  "ENGLISH",
  "ENGR",
  "ENVRES",
  "EPI",
  "EPS",
  "ESF",
  "ESOLLANG",
  "ESS",
  "ETHICSOC",
  "FAMMED",
  "FEMGEN",
  "FILILANG",
  "FILMEDIA",
  "FILMPROD",
  "FINANCE",
  "FINNLANG",
  "FRENCH",
  "FRENLANG",
  "GENE",
  "GEOLSCI",
  "GEOPHYS",
  "GEP",
  "GERLANG",
  "GERMAN",
  "GLOBAL",
  "GREELANG",
  "GSBGEN",
  "GSBGID",
  "GUJARLNG",
  "HAITLANG",
  "HAWALANG",
  "HEBRLANG",
  "HINDLANG",
  "HISTORY",
  "HITTLANG",
  "HNGRLANG",
  "HORSE",
  "HPS",
  "HRMGT",
  "HRP",
  "HUMBIO",
  "HUMCORE",
  "HUMRTS",
  "HUMSCI",
  "IIS",
  "IGBOLANG",
  "ILAC",
  "IMMUNOL",
  "INDE",
  "INUPQLNG",
  "INTLPOL",
  "INTNLREL",
  "ITALIAN",
  "ITALIC",
  "ITALLANG",
  "JAPAN",
  "JAPANLNG",
  "JEWISHST",
  "KAZKHLNG",
  "KHMRLANG",
  "KIN",
  "KINYLANG",
  "KOREA",
  "KORLANG",
  "LAKOTLNG",
  "LATINAM",
  "LAW",
  "LAWGEN",
  "LEAD",
  "LIFE",
  "LINGUIST",
  "LUGALANG",
  "MATH",
  "MATSCI",
  "MCP",
  "MCS",
  "ME",
  "MED",
  "MEDVLST",
  "MGTECON",
  "MI",
  "MKTG",
  "MLA",
  "MS&E",
  "MTL",
  "MUSIC",
  "NAHUALNG",
  "NATIVEAM",
  "NBIO",
  "NENS",
  "NEPR",
  "NSUR",
  "NVJOLANG",
  "OB",
  "OBGYN",
  "OCEANS",
  "OIT",
  "OPHT",
  "ORALCOMM",
  "ORTHO",
  "OSPAUSTL",
  "OSPBEIJ",
  "OSPBER",
  "OSPCPTWN",
  "OSPFLOR",
  "OSPGEN",
  "OSPHONGK",
  "OSPISTAN",
  "OSPKYOCT",
  "OSPKYOTO",
  "OSPMADRD",
  "OSPOXFRD",
  "OSPPARIS",
  "OSPSANTG",
  "OROMLANG",
  "OTOHNS",
  "OUTDOOR",
  "PAS",
  "PATH",
  "PEDS",
  "PERSLANG",
  "PHIL",
  "PHYSICS",
  "PHYSWELL",
  "POLECON",
  "POLISCI",
  "POLSHLNG",
  "PORTLANG",
  "PSYC",
  "PSYCH",
  "PUBLPOL",
  "PUNJLANG",
  "PWR",
  "QUECHLNG",
  "RAD",
  "RADO",
  "REES",
  "RELIGST",
  "RESPROG",
  "ROTCAF",
  "ROTCARMY",
  "ROTCNAVY",
  "ROMALANG",
  "RUSSLANG",
  "SAMOALNG",
  "SBIO",
  "SCCM",
  "SERBLANG",
  "SINY",
  "SIW",
  "SLAVIC",
  "SLVNLANG",
  "SLAVLANG",
  "SLE",
  "SNSKTLNG",
  "SOAR",
  "SOC",
  "SOMGEN",
  "SPANLANG",
  "SPECLANG",
  "STATS",
  "STEMREM",
  "STRAMGT",
  "STS",
  "SURG",
  "SUST",
  "SUSTAIN",
  "SYMSYS",
  "SWAHLANG",
  "TAMILANG",
  "TAPS",
  "THINK",
  "TIBETLNG",
  "TIGRYLNG",
  "TURKLANG",
  "TWILANG",
  "UAR",
  "URBANST",
  "UROL",
  "URDULANG",
  "UKRNLANG",
  "UYGHLANG",
  "VIETLANG",
  "VPTL",
  "WELLNESS",
  "YUPKLANG",
  "YDDSHLNG",
  "YORULANG",
  "ZULULANG",
] as const;
export const SubjectSchema = z.enum(SUBJECTS);

export const ACADEMIC_GROUPS = [
  "CSP",
  "DAPER",
  "EARTH",
  "EDUC",
  "ENGR",
  "GSB",
  "H&S",
  "LAW",
  "MED",
  "SUSTN",
  "VPTL",
  "VPUE",
] as const;
export const AcademicGroup = z.enum(ACADEMIC_GROUPS);

export const ACADEMIC_ORGANIZATIONS = [
  "AEROASTRO",
  "AFRICAST",
  "AFROAM",
  "AMSTU",
  "ANESTHESIA",
  "ANTHRO",
  "APPLPHYSIC",
  "ARCHAEOLGY",
  "ART",
  "ASIANLANG",
  "BIO",
  "BIOCHEM",
  "BIODATSCI",
  "BIOENGR",
  "BIOLSCIHOP",
  "BIOMEDINFO",
  "BIOPHYSICS",
  "BMP",
  "CARDTHSURG",
  "CHEMENGR",
  "CHEMISTRY",
  "CHPR",
  "CTRTCHLANG",
  "CIVENVRENG",
  "CLASSICS",
  "COMMUN",
  "COMPARLIT",
  "COMPARMED",
  "COMPUTSCI",
  "CSRE",
  "DAPER",
  "DATASCI",
  "DERMATOLGY",
  "DESIGN",
  "DEVBIOL",
  "DRAMA",
  "EARTHSYS",
  "EASTASNSTU",
  "ECONOMICS",
  "EDUCATION",
  "EESS",
  "EIPER",
  "ELECTENGR",
  "EMERGYMED",
  "ENGINEER",
  "ENGLISH",
  "ENVSOCSCI",
  "EPIDEM",
  "ETHICSOC",
  "FEMINST",
  "FRENCHITAL",
  "GENETICS",
  "GEOLSCI",
  "GEOPHYSICS",
  "GERMANSTU",
  "GSB",
  "GYNOBSTET",
  "HISPHSCI",
  "HISTORY",
  "HRP",
  "HUMANRIGHT",
  "HUMANRIGHTS",
  "HUMBIO",
  "HUMSCI",
  "HUMSCILCL",
  "ICA",
  "ICME",
  "IMMUNOLOGY",
  "INTERHUM",
  "INSTINTLST",
  "INTLPOLICY",
  "INTNLREL",
  "JEWISHST",
  "LANGCTR",
  "LATINAMSTU",
  "LAW",
  "LINGUISTIC",
  "MATH",
  "MATHCOMPSC",
  "MATSCI",
  "MECHENGR",
  "MEDDPT",
  "MEDICINE",
  "MGMTSCI",
  "MICROIMMUN",
  "MLA",
  "MOLCELLPHY",
  "MOLPHARM",
  "MTLIT",
  "MUSIC",
  "NEUROBIO",
  "NEURONEURO",
  "NEUROSCI",
  "NEUROSURG",
  "OCEANS",
  "OPHTHALMOL",
  "ORTHOPEDIC",
  "OTOLARYNG",
  "OVERSEAS",
  "PATHOLOGY",
  "PEDIATRICS",
  "PETROLENGR",
  "PHILOSOPHY",
  "PHYSICS",
  "POLITSCI",
  "PSYCHIATRY",
  "PSYCHOLOGY",
  "PUBLICPOL",
  "PWR",
  "RADIOLOGY",
  "RADONCOL",
  "REES",
  "RELIGST",
  "SAI",
  "SCCM",
  "SLAVIC",
  "SLE",
  "SOCIOLOGY",
  "SPANPORT",
  "STATISTICS",
  "STEMCELLS",
  "STRUCTBIOL",
  "STS",
  "SUPROGAUST",
  "SUPROGBEIJ",
  "SUPROGBERL",
  "SUPROGCAPE",
  "SUPROGFLOR",
  "SUPROGHONG",
  "SUPROGISTA",
  "SUPROGKYC",
  "SUPROGKYOT",
  "SUPROGMADR",
  "SUPROGNYC",
  "SUPROGOXFO",
  "SUPROGPARI",
  "SUPROGSANT",
  "SURGERY",
  "SUSTAIN",
  "SUSTSCI",
  "SYMBOLSYS",
  "URBANST",
  "UROLOGY",
  "VPTL",
  "VPUE",
  "CANCERBIO",
] as const;
export const AcademicOrganization = z.enum(ACADEMIC_ORGANIZATIONS);

/* =========================
   Type Exports (for convenience)
   ========================= */

export type ConsentOption = z.infer<typeof ConsentOption>;
export type FinalExamOption = z.infer<typeof FinalExamOption>;
export type ComponentType = z.infer<typeof ComponentType>;
export type EnrollStatus = z.infer<typeof EnrollStatus>;
export type InstructorRole = z.infer<typeof InstructorRole>;
export type EffectiveStatus = z.infer<typeof EffectiveStatus>;
export type AcademicCareer = z.infer<typeof AcademicCareer>;
export type GradingOption = z.infer<typeof GradingOption>;
export type GER = z.infer<typeof GER>;
export type Subject = z.infer<typeof SubjectSchema>;
export type AcademicGroup = z.infer<typeof AcademicGroup>;
export type AcademicOrganization = z.infer<typeof AcademicOrganization>;
