/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InstructorSunetRouteImport } from './routes/instructor.$sunet'
import { Route as CourseCourseIdRouteImport } from './routes/course.$courseId'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'

const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorSunetRoute = InstructorSunetRouteImport.update({
  id: '/instructor/$sunet',
  path: '/instructor/$sunet',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseCourseIdRoute = CourseCourseIdRouteImport.update({
  id: '/course/$courseId',
  path: '/course/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/courses': typeof CoursesRoute
  '/plan': typeof PlanRoute
  '/schedule': typeof ScheduleRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/course/$courseId': typeof CourseCourseIdRoute
  '/instructor/$sunet': typeof InstructorSunetRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/courses': typeof CoursesRoute
  '/plan': typeof PlanRoute
  '/schedule': typeof ScheduleRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/course/$courseId': typeof CourseCourseIdRoute
  '/instructor/$sunet': typeof InstructorSunetRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/courses': typeof CoursesRoute
  '/plan': typeof PlanRoute
  '/schedule': typeof ScheduleRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/course/$courseId': typeof CourseCourseIdRoute
  '/instructor/$sunet': typeof InstructorSunetRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/courses'
    | '/plan'
    | '/schedule'
    | '/auth/callback'
    | '/course/$courseId'
    | '/instructor/$sunet'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/courses'
    | '/plan'
    | '/schedule'
    | '/auth/callback'
    | '/course/$courseId'
    | '/instructor/$sunet'
  id:
    | '__root__'
    | '/'
    | '/courses'
    | '/plan'
    | '/schedule'
    | '/auth/callback'
    | '/course/$courseId'
    | '/instructor/$sunet'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CoursesRoute: typeof CoursesRoute
  PlanRoute: typeof PlanRoute
  ScheduleRoute: typeof ScheduleRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  CourseCourseIdRoute: typeof CourseCourseIdRoute
  InstructorSunetRoute: typeof InstructorSunetRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor/$sunet': {
      id: '/instructor/$sunet'
      path: '/instructor/$sunet'
      fullPath: '/instructor/$sunet'
      preLoaderRoute: typeof InstructorSunetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course/$courseId': {
      id: '/course/$courseId'
      path: '/course/$courseId'
      fullPath: '/course/$courseId'
      preLoaderRoute: typeof CourseCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CoursesRoute: CoursesRoute,
  PlanRoute: PlanRoute,
  ScheduleRoute: ScheduleRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  CourseCourseIdRoute: CourseCourseIdRoute,
  InstructorSunetRoute: InstructorSunetRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
